### ISSUE TITLE
部分路由无法跳转声明

### ISSUE THREAD

**Issue by songguoxiong** [qiqizjl/idea-plugin-hyperf#1]
https://github.com/qiqizjl/idea-plugin-hyperf/blob/15f9364329fe8c3d76dc871f95ded1868d046e97/src/main/java/com/naixiaoxin/idea/hyperf/controller/ControllerReferences.java#L38-L45

拼写错误hyperf -> yperf

**Comment by qiqizjl** [comment]
已更新1.0.2 等官方审核通过即可更新
